# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eTongDai' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eTongDai

  target 'eTongDai-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eTongDaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eTongDai-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eTongDai-tvOS

  target 'eTongDai-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eTongDaiNotifyService' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eTongDaiNotifyService

end
